<?php
namespace App\Framework;

use App\Config;
use Exception;
use PDO;
use PDOException;

class Repository
{
    private static ?PDO $connection = null;

    public function getConnection(): ?PDO
    {
        if (self::$connection === null) {
            $this->connect();
        }

        return self::$connection;
    }

    /**
     * Run a query and return all rows as associative arrays.
     *
     * @param array<string,mixed> $params
     * @return array<int,array<string,mixed>>
     */
    protected function fetchAll(string $sql, array $params = []): array
    {
        $stmt = $this->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }

    /**
     * Run a query and return the first row, or null if there are none.
     *
     * @param array<string,mixed> $params
     * @return array<string,mixed>|null
     */
    protected function fetchOne(string $sql, array $params = []): ?array
    {
        $stmt = $this->getConnection()->prepare($sql);
        $stmt->execute($params);
        $row = $stmt->fetch();
        return $row === false ? null : $row;
    }

    /**
     * Execute a write (INSERT/UPDATE/DELETE) and return affected row count.
     *
     * @param array<string,mixed> $params
     */
    protected function execute(string $sql, array $params = []): int
    {
        $stmt = $this->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->rowCount();
    }

    /**
     * Id generated by the most recent INSERT on this connection.
     */
    protected function lastInsertId(): int
    {
        return (int) $this->getConnection()->lastInsertId();
    }

    private function connect(): void
    {
        try {
            $dsn = 'mysql:host=' . Config::dbHost()
                 . ';port=' . Config::dbPort()
                 . ';dbname=' . Config::dbName()
                 . ';charset=utf8mb4';

            self::$connection = new PDO(
                $dsn,
                Config::dbUser(),
                Config::dbPass(),
                [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                ]
            );

        } catch (PDOException $ex) {
            throw new Exception('Database connection failed');
        }
    }
}
